# Generated by Django 6.1 on 2026-09-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='gravedad',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
