# Generated by Django 6.1 on 2026-09-20 21:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0002_alter_paciente_gravedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='dolor',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
