# Generated by Django 6.1 on 2026-09-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcion', '0003_alter_paciente_dolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='gravedad',
            field=models.CharField(blank=True, help_text='Opcional: se llena automáticamente según la dificultad respiratoria y el dolor.', max_length=50),
        ),
    ]
